/* Auto-generated by TanStack Router in normal builds. Kept here as a safe bootstrap. */
import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
});

export const routeTree = rootRoute.addChildren([IndexRoute]);
